server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://gondola.proxy.rlwy.net:41052/railway"
    username: "root"
    password: "yhnLlvlxzUMQmvdtFUKGwyxfxrHDzJtm"
  jpa:
    hibernate:
        ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false  # Dừng nếu có lỗi

  flyway:
    enabled: true

  thymeleaf:
    prefix: classpath:/Templates/

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ${EMAIL_USERNAME} # Đọc từ biến Railway
    password: ${EMAIL_PASSWORD} # Đọc từ biến Railway
    properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true

jwt:
  signerKey: "QnH/fRs+uwNd2FoCyreG4O1xAd0v3/lEX6pTTRTQzHea9YtyVYrpuTOj31XK9Y2D"


vnpay:
  pay-url:  "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "https://electric-car-maintenance.vercel.app/paymentSuccess"
  ipn-url: "https://electriccarmaintenancesystembackend-production.up.railway.app/api/vnpay/ipn"
  tmn-code: "9NN5ES27"
  secret-key: "9LKB82N3Z8HEIIACANJHCWIFDLF8HB9A"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"

mail:
  host: "smtp.gmail.com"
  port: 587
  username: ${EMAIL_USERNAME} # Sẽ đọc từ biến môi trường Railway
  password: ${EMAIL_PASSWORD} # Sẽ đọc từ biến môi trường Railway (Mật khẩu ứng dụng 16 chữ)
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
    mail.smtp.starttls.required: true
    mail.debug: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  packages-to-scan: com.group02.ev_maintenancesystem.controller




