server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:mysql://interchange.proxy.rlwy.net:59917/railway"
    username: "root"
    password: "LqlgUrmKyhsgyYFcQEWEfuyjMmAUNvgH"
  jpa:
    hibernate:
        ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false  # Dừng nếu có lỗi

  flyway:
    enabled: true

  thymeleaf:
    prefix: classpath:/templates/

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${EMAIL_USERNAME:trungtamxedienntntb@gmail.com}  # Fallback cho local
    password: ${EMAIL_PASSWORD:ycxrqwytcqfvlzbw}              # Fallback cho local
    properties:
      mail:
        smtp:
          ssl: true
          auth: true
          starttls:
            enable: true
            required: true
          debug: true

resend:
  api-key: "re_QQ6NwnAm_4nRY1fPh1bNj6HsW3EVpNWg8"
  from-email: "system@electriccare.id.vn"

jwt:
  signerKey: "QnH/fRs+uwNd2FoCyreG4O1xAd0v3/lEX6pTTRTQzHea9YtyVYrpuTOj31XK9Y2D"


vnpay:
  pay-url:  "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "https://electric-car-maintenance.vercel.app/paymentSuccess"
  ipn-url: "https://electriccarmaintenancesystembackend-production.up.railway.app/api/vnpay/ipn"
  tmn-code: "9NN5ES27"
  secret-key: "9LKB82N3Z8HEIIACANJHCWIFDLF8HB9A"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"



springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  packages-to-scan: com.group02.ev_maintenancesystem.controller




